# Generated by Django 4.0.1 on 2022-01-15 09:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='ticket',
            name='ticket_price',
            field=models.IntegerField(blank=True, default=20),
        ),
    ]
