# Generated by Django 4.0.1 on 2022-01-19 06:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_favorite'),
    ]

    operations = [
        migrations.RenameField(
            model_name='favorite',
            old_name='user',
            new_name='author',
        ),
    ]
