# Generated by Django 4.0.1 on 2022-01-19 06:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_rename_user_favorite_author'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='favorite',
            name='author',
        ),
    ]
